config/routes.rb
Rails.application.routes.draw do
  resources :bakers
  resources :articles

  root 'articles#index'

    get 'upvote/:id' => 'upvote#rise', :as => :upvote
    post 'upvote/:id' => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :upvotes

end

app/models/baker.rb
class Baker < ActiveRecord::Base
  #act_as_authentic
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :article 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json

  def rise
  end


  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'You threw out that bread.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body, :author, :upload, :entry_id)
    end
end

app/controllers/bakers_controller.rb
class BakersController < ApplicationController
  before_action :set_baker, only: [:show, :edit, :update, :destroy]

  # GET /bakers
  # GET /bakers.json
  def index
    @bakers = Baker.all
  end

  # GET /bakers/1
  # GET /bakers/1.json
  def show
  end

  # GET /bakers/new
  def new
    @baker = Baker.new
  end

  # GET /bakers/1/edit
  def edit
  end

  # POST /bakers
  # POST /bakers.json
  def create
    @baker = Baker.new(baker_params)

    respond_to do |format|
      if @baker.save
        format.html { redirect_to @baker, notice: 'You have been added to our list of Bakers!' }
        format.json { render :show, status: :created, location: @baker }
      else
        format.html { render :new }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bakers/1
  # PATCH/PUT /bakers/1.json
  def update
    respond_to do |format|
      if @baker.update(baker_params)
        format.html { redirect_to @baker, notice: 'Baker was successfully updated.' }
        format.json { render :show, status: :ok, location: @baker }
      else
        format.html { render :edit }
        format.json { render json: @baker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bakers/1
  # DELETE /bakers/1.json
  def destroy
    @baker.destroy
    respond_to do |format|
      format.html { redirect_to bakers_url, notice: 'Baker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_baker
      @baker = Baker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def baker_params
      params.require(:baker).permit(:username, :email, :crypted_password, :password_salt, :persistence_token)
    end
end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController

  def rise
    
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/bakers_helper.rb
module BakersHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Bread Name"  %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :"Bread Description" %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :"Baker" %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :"Best-by Date:" %><br>
    <%= f.datetime_select :upload %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Change the Recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back to Bakery', articles_path %>

app/views/articles/index.html.erb
<div class="background">
  <%=image_tag "bread-background.png"%>
</div>

  <p id="notice"><%= notice %></p>

  <h1>breaddit</h1>

  <table>
    <thead>
      <tr>
        <div id="tableheader">
          <th>Title</th>
          <th>Body</th>
          <th>Author</th>
          <th>Upload</th>
        </div>
      </tr>
    </thead>

    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <div class="rorf">
            <td><%= button_to '+1 Rise', upvote_path(:id)%>
            <td><%= link_to 'Flatten' %>
          </div>
          <td><%= article.title %></td>
          <td><%= article.body %></td>
          <td><%= article.author %></td>
          <td><%= article.upload %></td>
          <td><%= link_to 'Show', article %></td>
          <td><%= link_to 'Change Recipe', edit_article_path(article) %></td>
          <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you really throwing out this bread?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Add to Bread Basket', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Basket', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Upload:</strong>
  <%= @article.upload %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @article.entry_id %>
</p>

<%= link_to 'Change Recipe', edit_article_path(@article) %> |
<%= link_to 'Back to Bakery', articles_path %>

app/views/bakers/_form.html.erb
<%= form_for(@baker) do |f| %>
  <% if @baker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@baker.errors.count, "error") %> prohibited this baker from being added to our roster:</h2>

      <ul>
      <% @baker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bakers/edit.html.erb
<h1>Update Baker Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @baker %> |
<%= link_to 'Back', bakers_path %>

app/views/bakers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bakers</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bakers.each do |baker| %>
      <tr>
        <td><%= baker.username %></td>
        <td><%= baker.email %></td>
        <td><%= link_to 'Show', baker %></td>
        <td><%= link_to 'Edit', edit_baker_path(baker) %></td>
        <td><%= link_to 'Destroy', baker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Baker', new_baker_path %>

app/views/bakers/new.html.erb
<h1>Become a Baker!</h1>
<div class="background">
</div>



<%= render 'form' %>

<%= link_to 'Basket', articles_path %>

app/views/bakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @baker.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @baker.email %>
</p>

<%= link_to 'Update Baker Info', edit_baker_path(@baker) %> |
<%= link_to 'Basket', bakers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Breaddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="nav">
    <%= link_to "Sign up!", new_baker_path %>
  </div>



<%= yield %>

</body>
</html>